### ISSUE TITLE
there is a problem with tab+alt switching software animation scaling

### ISSUE THREAD

**Issue by wxmup** [dsheeler/CoverflowAltTab#256] opened 2024-09-10 04:56 UTC
My system is cachy os, using gnome 46.4.
In the wayland desktop environment, when I turn on monitor scaling that is not 100% (e.g., 200%), there is a problem with the switching animation of software in a non-maximized window, where the window the software is in doesn't drop at the expected animation drop point, but instead morphs and scales once.
When I set the monitor scaling to 100%, the problem goes away.
Alternatively, when I turn on fractional scaling, the command to use is: gsettings set org.gnome.mutter experimental-features “[‘scale-monitor-framebuffer’]”
At this point the monitor scaling was still 200%, but the issue disappeared.

**Comment by dsheeler** [comment] 2024-09-10 22:58
Thank you for reporting!  It's a known issue that is quite complicated to solve myself because it involves xwayland and how sometimes some apps use the scale factor and some don't, so you'd need a way to know that...  It was a mess. Hopefully fixed soon in gnome-shell if I understand things correctly.  Duplicate of https://github.com/dsheeler/CoverflowAltTab/issues/184

**Closed by dsheeler** 2024-09-10 22:58 UTC

**Comment by dsheeler** [comment] 2024-09-10 23:10
Oh, that's what I wanted to hear, also, that fractional scaling would fix this!!!
