### ISSUE TITLE
`Window Preview Size to Monitor Size Ratio` fails to take into consideration display scaling on Wayland

### ISSUE THREAD

**Issue by FelixFourcolor** [dsheeler/CoverflowAltTab#212] opened 2023-12-25 23:53 UTC
The property allows values from 0 to 1. However, if the display scaling is 200%, the value only goes up to 0.5; you can set it above 0.5, but it will be rendered the same as 0.5. And similarly if the display scaling is 300%, the value only goes up to 0.33. 

This bug is only seen on Wayland.

---------------------------------------------
Gnome 45
Extension v.70

**Comment by dsheeler** [comment] 2023-12-26 00:32
Hey thanks for the report! I'll look into this like now because I'm on holiday with nothing to do. Is this a new thing? Or seen in previous versions too?

**Comment by FelixFourcolor** [comment] 2023-12-26 01:27
If I remember correctly v.70 just came out today? Then I'm sure it's also in v.69, but I can't remember before that.

**Comment by dsheeler** [comment] 2023-12-26 02:10
Yes, v70 just today.  Thanks!

**Comment by FelixFourcolor** [comment] 2023-12-27 20:40
It seems that this behavior is also app-dependent. Most apps behave as I described above, but I found that vscode and steam are scaled properly.

To exaggerate the effect I show `Window Preview Size to Monitor Size Ratio`=1 and display scaling 300%.
[Screencast from 2023-12-27 12-34-55.webm](https://github.com/dmo60/CoverflowAltTab/assets/34260584/6ea579d0-0950-4a56-ab3b-e2c8b8cf2f01)

**Comment by dsheeler** [comment] 2024-01-08 05:37
duplicate of #184

**Comment by dsheeler** [comment] 2024-01-08 20:27
@FelixFourcolor, I don't fully understand the situation. It might be that xwayland apps don't work but native wayland apps do or vice versa. Or something more complicated, like some xwayland apps work and some don't...

**Comment by FelixFourcolor** [comment] 2024-01-08 21:15
@dsheeler I didn't think about it, but that makes sense. I think xwayland apps are scaled correctly, only native ones are broken.

**Comment by FelixFourcolor** [comment] 2024-06-03 22:36
@dsheeler any updates on this bug?

**Comment by dsheeler** [comment] 2024-06-03 23:23
No updates, sorry. My last comment still describes my state of understanding which is my understanding is incomplete. I feared it was the case that it's up to the application to scale properly in xwayland and I couldn't really do anything about it. I forget what the app needs to do at this point. I also find it hard to get motivated because I sitll use X11 and this is a "temporary" problem that exists only as long as xwayland is necessary. But how long will that be???

**Comment by FelixFourcolor** [comment] 2024-06-03 23:36
Unless I misinterpreted what you said, I think you got it the other way around. It's native wayland apps that don't scale properly, xwayland apps work.

**Comment by dsheeler** [comment] 2024-09-10 23:01
I'm going to close this one in favor of https://github.com/dsheeler/CoverflowAltTab/issues/184 of which this is a duplicate.

**Closed by dsheeler** 2024-09-10 23:01 UTC
